---
include:
  - board: nice_nano
    shield: cornepad_dongle
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y
  # - board: nice_nano
  #   shield: settings_reset
  # - board: nice_nano
  #   shield: cornepad_right
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
  # - board: nice_nano
  #   shield: cornepad_left
  #   cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
